// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

namespace AsmArm64;

/// <summary>
/// The kind of range prefetch operation for the RPRFM instruction.
/// </summary>
public enum Arm64RangePrefetchOperationKind : byte
{
    /// <summary>
    /// Not specified via an enum but through an immediate.
    /// </summary>
    None = 0,
    /// <summary>
    /// Prefetch Load, keep in cache.
    /// </summary>
    PLDKEEP = 0 + 1,
    /// <summary>
    /// Prefetch Store, keep in cache.
    /// </summary>
    PSTKEEP = 1 + 1,
    /// <summary>
    /// Prefetch Load, stream (do not retain in cache).
    /// </summary>
    PLDSTRM = 4 + 1,
    /// <summary>
    /// Prefetch Store, stream (do not retain in cache).
    /// </summary>
    PSTSTRM = 5 + 1,
}
