// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

namespace AsmArm64;

/// <summary>
/// The kind of range prefetch operation for the RPRFM instruction.
/// </summary>
public enum Arm64RangePrefetchOperationKind : byte
{
    /// <summary>
    /// Prefetch Load, keep in cache.
    /// </summary>
    PLDKEEP = 0,
    /// <summary>
    /// Prefetch Store, keep in cache.
    /// </summary>
    PSTKEEP = 1,
    /// <summary>
    /// Prefetch Load, stream (do not retain in cache).
    /// </summary>
    PLDSTRM = 4,
    /// <summary>
    /// Prefetch Store, stream (do not retain in cache).
    /// </summary>
    PSTSTRM = 5,
    /// <summary>
    /// Not specified via an enum but through an immediate.
    /// </summary>
    Undefined = 0xFF,
}

partial class Arm64Factory
{
    public static Arm64RangePrefetchOperationKind PLDKEEP => Arm64RangePrefetchOperationKind.PLDKEEP;
    public static Arm64RangePrefetchOperationKind PSTKEEP => Arm64RangePrefetchOperationKind.PSTKEEP;
    public static Arm64RangePrefetchOperationKind PLDSTRM => Arm64RangePrefetchOperationKind.PLDSTRM;
    public static Arm64RangePrefetchOperationKind PSTSTRM => Arm64RangePrefetchOperationKind.PSTSTRM;
}
