// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_BFM_General
{

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.BFM"/>.
    /// </summary>
    [TestMethod]
    public void Test_BFM_32m_bitfield_0()
    {

        {
            var raw = BFM(W0, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL W0, W1, #5, #1", asm);
        }

        {
            var raw = BFM(W15, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL W15, W1, #5, #1", asm);
        }

        {
            var raw = BFM(WZR, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL WZR, W1, #5, #1", asm);
        }

        {
            var raw = BFM(W0, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL W0, W16, #5, #1", asm);
        }

        {
            var raw = BFM(W15, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL W15, W16, #5, #1", asm);
        }

        {
            var raw = BFM(WZR, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL WZR, W16, #5, #1", asm);
        }

        {
            var raw = BFM(W0, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFC_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFC W0, #27, #6", asm);
        }

        {
            var raw = BFM(W15, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFC_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFC W15, #27, #6", asm);
        }

        {
            var raw = BFM(WZR, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFC_bfm_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFC WZR, #27, #6", asm);
        }
    }

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.BFM"/>.
    /// </summary>
    [TestMethod]
    public void Test_BFXIL_bfm_64m_bitfield_1()
    {

        {
            var raw = BFM(X0, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL X0, X1, #5, #1", asm);
        }

        {
            var raw = BFM(X15, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL X15, X1, #5, #1", asm);
        }

        {
            var raw = BFM(XZR, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL XZR, X1, #5, #1", asm);
        }

        {
            var raw = BFM(X0, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL X0, X16, #5, #1", asm);
        }

        {
            var raw = BFM(X15, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL X15, X16, #5, #1", asm);
        }

        {
            var raw = BFM(XZR, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFXIL_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFXIL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFXIL XZR, X16, #5, #1", asm);
        }

        {
            var raw = BFM(X0, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFC_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFC X0, #59, #6", asm);
        }

        {
            var raw = BFM(X15, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFC_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFC X15, #59, #6", asm);
        }

        {
            var raw = BFM(XZR, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.BFC_bfm_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.BFC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("BFC XZR, #59, #6", asm);
        }
    }
}
