// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_SMADDL_General
{

    /// <summary>
    /// Test of <see cref="SMADDL"/>.
    /// </summary>
    [TestMethod]
    public void Test_SMADDL_64wa_dp_3src_0()
    {

        {
            var raw = SMADDL(X0, W1, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, W2, X3", asm);
        }

        {
            var raw = SMADDL(X15, W1, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, W2, X3", asm);
        }

        {
            var raw = SMADDL(XZR, W1, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, W2, X3", asm);
        }

        {
            var raw = SMADDL(X0, W16, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, W2, X3", asm);
        }

        {
            var raw = SMADDL(X15, W16, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, W2, X3", asm);
        }

        {
            var raw = SMADDL(XZR, W16, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, W2, X3", asm);
        }

        {
            var raw = SMADDL(X0, WZR, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, W2, X3", asm);
        }

        {
            var raw = SMADDL(X15, WZR, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, W2, X3", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, W2, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, W2, X3", asm);
        }

        {
            var raw = SMADDL(X0, W1, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, W17, X3", asm);
        }

        {
            var raw = SMADDL(X15, W1, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, W17, X3", asm);
        }

        {
            var raw = SMADDL(XZR, W1, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, W17, X3", asm);
        }

        {
            var raw = SMADDL(X0, W16, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, W17, X3", asm);
        }

        {
            var raw = SMADDL(X15, W16, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, W17, X3", asm);
        }

        {
            var raw = SMADDL(XZR, W16, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, W17, X3", asm);
        }

        {
            var raw = SMADDL(X0, WZR, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, W17, X3", asm);
        }

        {
            var raw = SMADDL(X15, WZR, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, W17, X3", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, W17, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, W17, X3", asm);
        }

        {
            var raw = SMADDL(X0, W1, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, WZR, X3", asm);
        }

        {
            var raw = SMADDL(X15, W1, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, WZR, X3", asm);
        }

        {
            var raw = SMADDL(XZR, W1, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, WZR, X3", asm);
        }

        {
            var raw = SMADDL(X0, W16, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, WZR, X3", asm);
        }

        {
            var raw = SMADDL(X15, W16, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, WZR, X3", asm);
        }

        {
            var raw = SMADDL(XZR, W16, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, WZR, X3", asm);
        }

        {
            var raw = SMADDL(X0, WZR, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, WZR, X3", asm);
        }

        {
            var raw = SMADDL(X15, WZR, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, WZR, X3", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, WZR, X3);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, WZR, X3", asm);
        }

        {
            var raw = SMADDL(X0, W1, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, W2, X18", asm);
        }

        {
            var raw = SMADDL(X15, W1, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, W2, X18", asm);
        }

        {
            var raw = SMADDL(XZR, W1, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, W2, X18", asm);
        }

        {
            var raw = SMADDL(X0, W16, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, W2, X18", asm);
        }

        {
            var raw = SMADDL(X15, W16, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, W2, X18", asm);
        }

        {
            var raw = SMADDL(XZR, W16, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, W2, X18", asm);
        }

        {
            var raw = SMADDL(X0, WZR, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, W2, X18", asm);
        }

        {
            var raw = SMADDL(X15, WZR, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, W2, X18", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, W2, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, W2, X18", asm);
        }

        {
            var raw = SMADDL(X0, W1, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, W17, X18", asm);
        }

        {
            var raw = SMADDL(X15, W1, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, W17, X18", asm);
        }

        {
            var raw = SMADDL(XZR, W1, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, W17, X18", asm);
        }

        {
            var raw = SMADDL(X0, W16, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, W17, X18", asm);
        }

        {
            var raw = SMADDL(X15, W16, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, W17, X18", asm);
        }

        {
            var raw = SMADDL(XZR, W16, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, W17, X18", asm);
        }

        {
            var raw = SMADDL(X0, WZR, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, W17, X18", asm);
        }

        {
            var raw = SMADDL(X15, WZR, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, W17, X18", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, W17, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, W17, X18", asm);
        }

        {
            var raw = SMADDL(X0, W1, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, WZR, X18", asm);
        }

        {
            var raw = SMADDL(X15, W1, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, WZR, X18", asm);
        }

        {
            var raw = SMADDL(XZR, W1, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, WZR, X18", asm);
        }

        {
            var raw = SMADDL(X0, W16, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, WZR, X18", asm);
        }

        {
            var raw = SMADDL(X15, W16, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, WZR, X18", asm);
        }

        {
            var raw = SMADDL(XZR, W16, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, WZR, X18", asm);
        }

        {
            var raw = SMADDL(X0, WZR, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, WZR, X18", asm);
        }

        {
            var raw = SMADDL(X15, WZR, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, WZR, X18", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, WZR, X18);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, WZR, X18", asm);
        }

        {
            var raw = SMADDL(X0, W1, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, W2, XZR", asm);
        }

        {
            var raw = SMADDL(X15, W1, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, W2, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, W1, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, W2, XZR", asm);
        }

        {
            var raw = SMADDL(X0, W16, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, W2, XZR", asm);
        }

        {
            var raw = SMADDL(X15, W16, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, W2, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, W16, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, W2, XZR", asm);
        }

        {
            var raw = SMADDL(X0, WZR, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, W2, XZR", asm);
        }

        {
            var raw = SMADDL(X15, WZR, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, W2, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, W2, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, W2, XZR", asm);
        }

        {
            var raw = SMADDL(X0, W1, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, W17, XZR", asm);
        }

        {
            var raw = SMADDL(X15, W1, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, W17, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, W1, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, W17, XZR", asm);
        }

        {
            var raw = SMADDL(X0, W16, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, W17, XZR", asm);
        }

        {
            var raw = SMADDL(X15, W16, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, W17, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, W16, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, W17, XZR", asm);
        }

        {
            var raw = SMADDL(X0, WZR, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, W17, XZR", asm);
        }

        {
            var raw = SMADDL(X15, WZR, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, W17, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, W17, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, W17, XZR", asm);
        }

        {
            var raw = SMADDL(X0, W1, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W1, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(X15, W1, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W1, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, W1, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W1, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(X0, W16, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, W16, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(X15, W16, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, W16, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, W16, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, W16, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(X0, WZR, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X0, WZR, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(X15, WZR, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL X15, WZR, WZR, XZR", asm);
        }

        {
            var raw = SMADDL(XZR, WZR, WZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SMADDL_64wa_dp_3src, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SMADDL, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SMADDL XZR, WZR, WZR, XZR", asm);
        }
    }
}
