// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_SBFM_General
{

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.SBFM"/>.
    /// </summary>
    [TestMethod]
    public void Test_SBFM_32m_bitfield_0()
    {

        {
            var raw = SBFM(W0, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM W0, W1, #5, #5", asm);
        }

        {
            var raw = SBFM(W15, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM W15, W1, #5, #5", asm);
        }

        {
            var raw = SBFM(WZR, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM WZR, W1, #5, #5", asm);
        }

        {
            var raw = SBFM(W0, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM W0, W16, #5, #5", asm);
        }

        {
            var raw = SBFM(W15, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM W15, W16, #5, #5", asm);
        }

        {
            var raw = SBFM(WZR, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM WZR, W16, #5, #5", asm);
        }

        {
            var raw = SBFM(W0, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM W0, WZR, #5, #5", asm);
        }

        {
            var raw = SBFM(W15, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM W15, WZR, #5, #5", asm);
        }

        {
            var raw = SBFM(WZR, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM WZR, WZR, #5, #5", asm);
        }
    }

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.SBFM"/>.
    /// </summary>
    [TestMethod]
    public void Test_SBFM_64m_bitfield_1()
    {

        {
            var raw = SBFM(X0, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM X0, X1, #5, #5", asm);
        }

        {
            var raw = SBFM(X15, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM X15, X1, #5, #5", asm);
        }

        {
            var raw = SBFM(XZR, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM XZR, X1, #5, #5", asm);
        }

        {
            var raw = SBFM(X0, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM X0, X16, #5, #5", asm);
        }

        {
            var raw = SBFM(X15, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM X15, X16, #5, #5", asm);
        }

        {
            var raw = SBFM(XZR, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM XZR, X16, #5, #5", asm);
        }

        {
            var raw = SBFM(X0, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM X0, XZR, #5, #5", asm);
        }

        {
            var raw = SBFM(X15, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM X15, XZR, #5, #5", asm);
        }

        {
            var raw = SBFM(XZR, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBFM XZR, XZR, #5, #5", asm);
        }
    }
}
