// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_SBC_General
{

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.SBC"/>.
    /// </summary>
    [TestMethod]
    public void Test_SBC_32_addsub_carry_0()
    {

        {
            var raw = SBC(W0, W1, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, W1, W2", asm);
        }

        {
            var raw = SBC(W15, W1, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, W1, W2", asm);
        }

        {
            var raw = SBC(WZR, W1, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, W1, W2", asm);
        }

        {
            var raw = SBC(W0, W16, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, W16, W2", asm);
        }

        {
            var raw = SBC(W15, W16, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, W16, W2", asm);
        }

        {
            var raw = SBC(WZR, W16, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, W16, W2", asm);
        }

        {
            var raw = SBC(W0, WZR, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, WZR, W2", asm);
        }

        {
            var raw = SBC(W15, WZR, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, WZR, W2", asm);
        }

        {
            var raw = SBC(WZR, WZR, W2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, WZR, W2", asm);
        }

        {
            var raw = SBC(W0, W1, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, W1, W17", asm);
        }

        {
            var raw = SBC(W15, W1, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, W1, W17", asm);
        }

        {
            var raw = SBC(WZR, W1, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, W1, W17", asm);
        }

        {
            var raw = SBC(W0, W16, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, W16, W17", asm);
        }

        {
            var raw = SBC(W15, W16, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, W16, W17", asm);
        }

        {
            var raw = SBC(WZR, W16, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, W16, W17", asm);
        }

        {
            var raw = SBC(W0, WZR, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, WZR, W17", asm);
        }

        {
            var raw = SBC(W15, WZR, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, WZR, W17", asm);
        }

        {
            var raw = SBC(WZR, WZR, W17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, WZR, W17", asm);
        }

        {
            var raw = SBC(W0, W1, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, W1, WZR", asm);
        }

        {
            var raw = SBC(W15, W1, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, W1, WZR", asm);
        }

        {
            var raw = SBC(WZR, W1, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, W1, WZR", asm);
        }

        {
            var raw = SBC(W0, W16, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, W16, WZR", asm);
        }

        {
            var raw = SBC(W15, W16, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, W16, WZR", asm);
        }

        {
            var raw = SBC(WZR, W16, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, W16, WZR", asm);
        }

        {
            var raw = SBC(W0, WZR, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W0, WZR, WZR", asm);
        }

        {
            var raw = SBC(W15, WZR, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC W15, WZR, WZR", asm);
        }

        {
            var raw = SBC(WZR, WZR, WZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_32_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC WZR, WZR, WZR", asm);
        }
    }

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.SBC"/>.
    /// </summary>
    [TestMethod]
    public void Test_SBC_64_addsub_carry_1()
    {

        {
            var raw = SBC(X0, X1, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, X1, X2", asm);
        }

        {
            var raw = SBC(X15, X1, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, X1, X2", asm);
        }

        {
            var raw = SBC(XZR, X1, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, X1, X2", asm);
        }

        {
            var raw = SBC(X0, X16, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, X16, X2", asm);
        }

        {
            var raw = SBC(X15, X16, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, X16, X2", asm);
        }

        {
            var raw = SBC(XZR, X16, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, X16, X2", asm);
        }

        {
            var raw = SBC(X0, XZR, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, XZR, X2", asm);
        }

        {
            var raw = SBC(X15, XZR, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, XZR, X2", asm);
        }

        {
            var raw = SBC(XZR, XZR, X2);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, XZR, X2", asm);
        }

        {
            var raw = SBC(X0, X1, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, X1, X17", asm);
        }

        {
            var raw = SBC(X15, X1, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, X1, X17", asm);
        }

        {
            var raw = SBC(XZR, X1, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, X1, X17", asm);
        }

        {
            var raw = SBC(X0, X16, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, X16, X17", asm);
        }

        {
            var raw = SBC(X15, X16, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, X16, X17", asm);
        }

        {
            var raw = SBC(XZR, X16, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, X16, X17", asm);
        }

        {
            var raw = SBC(X0, XZR, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, XZR, X17", asm);
        }

        {
            var raw = SBC(X15, XZR, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, XZR, X17", asm);
        }

        {
            var raw = SBC(XZR, XZR, X17);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, XZR, X17", asm);
        }

        {
            var raw = SBC(X0, X1, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, X1, XZR", asm);
        }

        {
            var raw = SBC(X15, X1, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, X1, XZR", asm);
        }

        {
            var raw = SBC(XZR, X1, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, X1, XZR", asm);
        }

        {
            var raw = SBC(X0, X16, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, X16, XZR", asm);
        }

        {
            var raw = SBC(X15, X16, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, X16, XZR", asm);
        }

        {
            var raw = SBC(XZR, X16, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, X16, XZR", asm);
        }

        {
            var raw = SBC(X0, XZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X0, XZR, XZR", asm);
        }

        {
            var raw = SBC(X15, XZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC X15, XZR, XZR", asm);
        }

        {
            var raw = SBC(XZR, XZR, XZR);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.SBC_64_addsub_carry, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.SBC, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("SBC XZR, XZR, XZR", asm);
        }
    }
}
