// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_MOV_MOVN_General
{

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.MOV_MOVN"/>.
    /// </summary>
    [TestMethod]
    public void Test_MOV_movn_32_movewide_0()
    {

        {
            var raw = MOV(W0, Shift64(4660, 16));
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOV_movn_32_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOV, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOV W0, #305397760", asm);
        }

        {
            var raw = MOV(W15, Shift64(4660, 16));
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOV_movn_32_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOV, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOV W15, #305397760", asm);
        }

        {
            var raw = MOV(WZR, Shift64(4660, 16));
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOV_movn_32_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOV, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOV WZR, #305397760", asm);
        }
    }

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.MOV_MOVN"/>.
    /// </summary>
    [TestMethod]
    public void Test_MOV_movn_64_movewide_1()
    {

        {
            var raw = MOV(X0, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOV_movn_64_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOV, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOV X0, #5", asm);
        }

        {
            var raw = MOV(X15, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOV_movn_64_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOV, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOV X15, #5", asm);
        }

        {
            var raw = MOV(XZR, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOV_movn_64_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOV, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOV XZR, #5", asm);
        }
    }
}
