// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_UBFM_General
{

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.UBFM"/>.
    /// </summary>
    [TestMethod]
    public void Test_UBFM_32m_bitfield_0()
    {

        {
            var raw = UBFM(W0, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM W0, W1, #5, #5", asm);
        }

        {
            var raw = UBFM(W15, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM W15, W1, #5, #5", asm);
        }

        {
            var raw = UBFM(WZR, W1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM WZR, W1, #5, #5", asm);
        }

        {
            var raw = UBFM(W0, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM W0, W16, #5, #5", asm);
        }

        {
            var raw = UBFM(W15, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM W15, W16, #5, #5", asm);
        }

        {
            var raw = UBFM(WZR, W16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM WZR, W16, #5, #5", asm);
        }

        {
            var raw = UBFM(W0, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM W0, WZR, #5, #5", asm);
        }

        {
            var raw = UBFM(W15, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM W15, WZR, #5, #5", asm);
        }

        {
            var raw = UBFM(WZR, WZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_32m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM WZR, WZR, #5, #5", asm);
        }
    }

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.UBFM"/>.
    /// </summary>
    [TestMethod]
    public void Test_UBFM_64m_bitfield_1()
    {

        {
            var raw = UBFM(X0, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM X0, X1, #5, #5", asm);
        }

        {
            var raw = UBFM(X15, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM X15, X1, #5, #5", asm);
        }

        {
            var raw = UBFM(XZR, X1, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM XZR, X1, #5, #5", asm);
        }

        {
            var raw = UBFM(X0, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM X0, X16, #5, #5", asm);
        }

        {
            var raw = UBFM(X15, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM X15, X16, #5, #5", asm);
        }

        {
            var raw = UBFM(XZR, X16, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM XZR, X16, #5, #5", asm);
        }

        {
            var raw = UBFM(X0, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM X0, XZR, #5, #5", asm);
        }

        {
            var raw = UBFM(X15, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM X15, XZR, #5, #5", asm);
        }

        {
            var raw = UBFM(XZR, XZR, 5, 5);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.UBFM_64m_bitfield, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.UBFM, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("UBFM XZR, XZR, #5, #5", asm);
        }
    }
}
