// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
// ------------------------------------------------------------------------------
// This code was generated by AsmArm64.CodeGen.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// ------------------------------------------------------------------------------
// ReSharper disable All
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using static AsmArm64.Arm64InstructionFactory;
using static AsmArm64.Arm64Factory;
namespace AsmArm64.Tests.manual;

[TestClass]
public class Arm64InstructionFactoryTests_MOVN_General
{

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.MOVN"/>.
    /// </summary>
    [TestMethod]
    public void Test_MOVN_32_movewide_0()
    {

        {
            var raw = MOVN(W0, 5, _LSL, 16);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOVN_32_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOVN, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOVN W0, #5, LSL #16", asm);
        }

        {
            var raw = MOVN(W15, 5, _LSL, 16);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOVN_32_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOVN, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOVN W15, #5, LSL #16", asm);
        }

        {
            var raw = MOVN(WZR, 5, _LSL, 16);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOVN_32_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOVN, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOVN WZR, #5, LSL #16", asm);
        }
    }

    /// <summary>
    /// Test of <see cref="Arm64InstructionFactory.MOVN"/>.
    /// </summary>
    [TestMethod]
    public void Test_MOVN_64_movewide_1()
    {

        {
            var raw = MOVN(X0, 5, _LSL, 16);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOVN_64_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOVN, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOVN X0, #5, LSL #16", asm);
        }

        {
            var raw = MOVN(X15, 5, _LSL, 16);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOVN_64_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOVN, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOVN X15, #5, LSL #16", asm);
        }

        {
            var raw = MOVN(XZR, 5, _LSL, 16);
            var instruction = Arm64Instruction.Decode(raw);
            Assert.AreEqual(Arm64InstructionId.MOVN_64_movewide, instruction.Id);
            Assert.AreEqual(Arm64Mnemonic.MOVN, instruction.Mnemonic);
            var asm = instruction.ToString("H", null);
            Assert.AreEqual("MOVN XZR, #5, LSL #16", asm);
        }
    }
}
