name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'readme.md'
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      actions: write
      contents: write
    runs-on: 'windows-latest'
    steps:
      - name: NuGet Login
        if: ${{ github.event_name == 'push' && github.repository_owner == 'xoofx' }}
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: xoofx
      - name: "Build, Test, Pack and Publish"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main
        with:
          NUGET_TOKEN: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}